version: '2'

services:
  consul:
    command: -server -bootstrap
    image: progrium/consul
    network_mode: "host"
    ports:
      - "8500:8500"

  bookbrainz:
    build:
        context: ..
        dockerfile: ./Dockerfile
    network_mode: "host"
    ports:
      - "80:9099"

  pgbouncer-master:
    image: postgres:9.5
    network_mode: "host"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.5

  bookbrainz-redis:
    image: redis:3.2-alpine
    network_mode: "bridge"
    command: "redis-server --appendonly yes"
